// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfRSgl5Q-_VIPrujWSMIlNz7p32JIf-k',
    appId: '1:38568941354:web:7ced7fe2f7b0e25511f053',
    messagingSenderId: '38568941354',
    projectId: 'pashu-bazaar-a9d94',
    authDomain: 'pashu-bazaar-a9d94.firebaseapp.com',
    storageBucket: 'pashu-bazaar-a9d94.firebasestorage.app',
    measurementId: 'G-FX5QHC8YMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYsCGIxrgDftlNOmEATyR9DTbGMz7aG4',
    appId: '1:38568941354:android:be1a34486ff3db4611f053',
    messagingSenderId: '38568941354',
    projectId: 'pashu-bazaar-a9d94',
    storageBucket: 'pashu-bazaar-a9d94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSIxmhrknkdnIvbFix_B0y5_TONr_Qfsw',
    appId: '1:38568941354:ios:f52755a7346b415611f053',
    messagingSenderId: '38568941354',
    projectId: 'pashu-bazaar-a9d94',
    storageBucket: 'pashu-bazaar-a9d94.firebasestorage.app',
    iosBundleId: 'com.example.pashuBazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSIxmhrknkdnIvbFix_B0y5_TONr_Qfsw',
    appId: '1:38568941354:ios:f52755a7346b415611f053',
    messagingSenderId: '38568941354',
    projectId: 'pashu-bazaar-a9d94',
    storageBucket: 'pashu-bazaar-a9d94.firebasestorage.app',
    iosBundleId: 'com.example.pashuBazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfRSgl5Q-_VIPrujWSMIlNz7p32JIf-k',
    appId: '1:38568941354:web:9de78df53be5a68011f053',
    messagingSenderId: '38568941354',
    projectId: 'pashu-bazaar-a9d94',
    authDomain: 'pashu-bazaar-a9d94.firebaseapp.com',
    storageBucket: 'pashu-bazaar-a9d94.firebasestorage.app',
    measurementId: 'G-W145SL5T07',
  );

}